spring.application.name=customer-management

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/customer_management}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret=${JWT_SECRET}

# ReactのURL
app.frontend-url=${FRONTEND_URL:http://localhost:5173}

# Spring Securityのログ
logging.level.org.springframework.security=INFO